import { normalizeText, correctStructuredNumbers } from './src/engine/fieldMatcher';

// Test various real-world OCR outputs for Coffee Jar and other products

const sample1 = `SOLUBLE COFFEE POWDER
INGREDIENT: COFFEE BEANS
MARKETED BY: AVENUE SUPERMARTS LTD. (ASL),
ANJANEYA CHS LIMITED, ORCHARD AVENUE,
POWAI, MUMBAI - 400076, MAHARASHTRA.
fssai Lic. No. 10018022008191
MANUFACTURED BY: TATA CONSUMER PRODUCTS LTD.,
MEDAK, TELANGANA- 502334.
FOR FEEDBACK / SUGGESTIONS,
PLEASE CONTACT CONSUMER CARE EXECUTIVE AT 'MARKETED BY' ADDRESS,
EMAIL: SUGGESTION@DMARTINDIA.COM,
PHONE: 022 71230555.
NET QUANTITY : 100g
MRP ₹ (incl. of all taxes) : 303.00
UNIT SALE PRICE ₹ : 3.03/g
DATE OF PACKAGING + DEC/2025`;

const sample2_multiline = `SOLUBLE COFFEE POWDER
MARKETED BY: AVENUE SUPERMARTS LTD, MUMBAI 400076
FOR FEEDBACK / SUGGESTIONS
PLEASE CONTACT CONSUMER CARE
EMAIL: SUGGESTION©DMARTINDIA.COM
PHONE: O22 71230555
NET QUANTITY: 100g
MRP ₹ (incl. of all taxes)
: 303.00
UNIT SALE PRICE: 3.03/g
DATE OF PACKAGING: DEC/2025`;

console.log('Testing regexes...');
